filter:
    excluded_paths: [node_modules/*, build/*, lib/*, test/*]
build:
  nodes:
    analysis:
      tests:
        override:
          - js-scrutinizer-run
          - command: eslint-run
            use_website_config: true